blogicum/blog/urls.py
from django.urls import path

from .views import (
    index,
    post_detail,
    category_posts,
)

app_name = 'blog'

urlpatterns = [
    path(
        route='',
        view=index,
        name='index',
    ),
    path(
        route='posts/<int:post_id>/',
        view=post_detail,
        name='post_detail',
    ),
    path(
        route='category/<slug:category_slug>/',
        view=category_posts,
        name='category_posts',
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
]

blogicum/pages/urls.py
from django.urls import path

from .views import about, rules


app_name = 'pages'

urlpatterns = [
    path(
        route='about/',
        view=about,
        name='about',
    ),
    path(
        route='rules/',
        view=rules,
        name='rules',
    ),
]

blogicum/blog/views.py
from django.shortcuts import render
from django.http import Http404

posts = [
    {
        'id': 0,
        'location': 'Остров отчаянья',
        'date': '30 сентября 1659 года',
        'category': 'travel',
        'text': '''Наш корабль, застигнутый в открытом море
                страшным штормом, потерпел крушение.
                Весь экипаж, кроме меня, утонул; я же,
                несчастный Робинзон Крузо, был выброшен
                полумёртвым на берег этого проклятого острова,
                который назвал островом Отчаяния.''',
    },
    {
        'id': 1,
        'location': 'Остров отчаянья',
        'date': '1 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Проснувшись поутру, я увидел, что наш корабль сняло
                с мели приливом и пригнало гораздо ближе к берегу.
                Это подало мне надежду, что, когда ветер стихнет,
                мне удастся добраться до корабля и запастись едой и
                другими необходимыми вещами. Я немного приободрился,
                хотя печаль о погибших товарищах не покидала меня.
                Мне всё думалось, что, останься мы на корабле, мы
                непременно спаслись бы. Теперь из его обломков мы могли бы
                построить баркас, на котором и выбрались бы из этого
                гиблого места.''',
    },
    {
        'id': 2,
        'location': 'Остров отчаянья',
        'date': '25 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Всю ночь и весь день шёл дождь и дул сильный
                порывистый ветер. 25 октября.  Корабль за ночь разбило
                в щепки; на том месте, где он стоял, торчат какие-то
                жалкие обломки,  да и те видны только во время отлива.
                Весь этот день я хлопотал  около вещей: укрывал и
                укутывал их, чтобы не испортились от дождя.''',
    },
]


posts_dict = {post['id']: post for post in posts}


def index(request):
    """View функция - лента записей."""
    template = 'blog/index.html'
    context = {
        "posts": posts[::-1],
    }
    return render(
        request=request,
        template_name=template,
        context=context,
    )


def post_detail(request, post_id):
    """View функция - конкретная выбранная запись в ленте."""
    current_post = posts_dict.get(post_id)
    if not current_post:
        raise Http404('Пост с таким идентификатором не существует.')

    template = 'blog/detail.html'
    context = {
        "post": current_post,
    }
    return render(
        request=request,
        template_name=template,
        context=context,
    )


def category_posts(request, category_slug):
    """View функция - категория постов."""
    template = 'blog/category.html'
    matching_posts = [post for post in posts if post['category'] == category_slug]
    context = {
        'category': category_slug,
        'posts': matching_posts,
    }
    return render(
        request=request,
        template_name=template,
        context=context,
    )

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    """View функция - раздел 'О проекте'."""
    template = 'pages/about.html'
    return render(
        request=request,
        template_name=template,
    )


def rules(request):
    """View функция - раздел 'Наши правила'."""
    template = 'pages/rules.html'
    return render(
        request=request,
        template_name=template,
    )

blogicum/templates/base.html
<!DOCTYPE html>
<html lang="ru"> 
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>	   
    {% include 'includes/header.html' %}
    <main>
      {% block content %}{% endblock %}
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}

{% block title %}
  Публикации в категории - {{ category }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>Публикации в категории - {{ category }}</h1>
    {% for post in posts %}
      <hr>
      <article>
        <ul>
          <li>
            Место: {{ post.location }}
          </li>
          <li>
            Дата: {{ post.date }}
          </li>
          <li>
            Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
          </li>
        </ul>
        <p>
          {{ post.text|truncatewords:10 }}
        </p>
        <a href="{% url 'blog:post_detail' post.id %}">Читать полный текст</a>
      </article>
    {% endfor %}
  </div>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}

{% block title %}
  {{ post.location }}. {{ post.date }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <article>
      <ul>
        <li>
          Место: {{ post.location }}
        </li>
        <li>
          Дата: {{ post.date }}
        </li>
        <li>
          Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
        </li>
      </ul>
      <p>
        {{ post.text }}
      </p>
    </article>
  </div>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}

{% block title %}
  Лента записей
{% endblock %}

{% block content %}
  <h1>Лента записей</h1>
  {% for post in posts %}
    <article>
      <ul>
        <li>
          Место: {{ post.location }}
        </li>
        <li>
          Дата: {{ post.date }}
        </li>
        <li>
          Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
        </li>
      </ul>
      <p>
        {{ post.text|truncatewords:10 }}
      </p>
      <a href="{% url 'blog:post_detail' post.id %}">Читать полный текст</a>
    </article>
  {% endfor %}
{% endblock %}

blogicum/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>
</footer>

blogicum/templates/includes/header.html
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
          {% load static %}
          <img 
            src="{% static 'img/logo.png' %}"
            width="30"
            height="30"
            class="d-inline-block align-top" alt=""
            >
          Блогикум
      </a>
      <ul class="nav  nav-pills">
          <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'blog:index' %}active{% endif %}"
            href="{% url 'blog:index' %}"
            >
              Лента записей
          </a>
          </li>
          <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'pages:about' %}active{% endif %}"
            href="{% url 'pages:about' %}"
            >
              О проекте
          </a>
          </li>
          <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'pages:rules' %}active{% endif %}"
            href="{% url 'pages:rules' %}"
            >
              Наши правила
          </a>
          </li>
      </ul>
      </div>
  </nav>
</header>
{% endwith %}

blogicum/templates/pages/about.html
{% extends "base.html" %}

{% block title %}
  Об авторе
{% endblock %}

{% block content %}
  <h1>Об авторе</h1>
  <p>
    Информация об авторе блога.
  </p>
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}

{% block title %}
  Правила
{% endblock %}

{% block content %}
  <h1>Правила</h1>
  <p>
    Правила нашего сайта.
  </p>
{% endblock %}